using System;

public enum PieceType
{
	Chip,
	RocketPiece,
	PowerupChip,
	SlotLight,
	Net,
	MultiLayerItem,
	Pipe,
	JumpRamp,
	ConveyorBelt,
	SeekingMissile,
	ChipDestroyParticles,
	LightingBolt,
	FallingElementExit,
	SlotColorSlate,
	BurriedBunny,
	CarpetSpread,
	WallBlocker,
	ConveyorBeltPlate,
	MovingElement,
	SlotBackLight,
	LightingBoltChip,
	ChipFeather,
	LightingBoltPowerup,
	BubblePiece,
	MonsterElement,
	FlyingSaucer,
	HammerAnimation,
	Coin,
	MagicHatBomb,
	PointsDisplay,
	SpecialGenerator
}
